### ISSUE TITLE
Is it possible to get FLAME 51 landmark from the final Head Models?

### ISSUE THREAD

**Issue by doublexxking** [SimonGiebenhain/NPHM#12]
As title mentioned, are there some methods to get FLAME 51 landmark? Many evaluations need the results of landmark..

**Comment by SimonGiebenhain** [comment]
Hey,
unfortunately, that is not possible due to the nature of our identity space, which is represented as an SDF.

If you are interested in similar methods, maybe the i3DMM or ImFace models could do that, since they model the identity as a deformation from a template, on which it could be possible to define these landmarks

Kind regards,
Simon
