### ISSUE TITLE
Broken data (version2)

### ISSUE THREAD

**Issue by jseobyun** [SimonGiebenhain/NPHM#22]
Hi the authors. thank you for publishing awesome works. 

A week ago, I requested data access and have processed it.  (version 2)

During postprocessing, I encounter broken data (not a few, quite many samples)

For example, chunk005/104/002 is like below (for preventing undesired problem, I capture only back-side)

![image](https://github.com/user-attachments/assets/e3665bed-505a-4251-a47e-d8962aebccc4)

As you can see, the vertices of top head are broken. 

Additionally some data have broken textures (e.g. top head contains textures from clothes)

I guess that there are some scale and range(coordinates) issues during optimization.

Could you check these files? unfortunately I fail to list-up broken files.

**Comment by SimonGiebenhain** [comment]
Hi jseobyun,

you are totally correct. A few scans have issues. For example the one that you are sharing. Here we placed the participant too high inside out scanning set-up. Therefore the upper part of his head was out-of-bounds. (We didn't realize this issue until a few days later and in that time we scanned a few more people with the same problem).

The reconstruction software attempts to smoothly interpolate the missing regions.
To exclude this pattern from any learned prior, I adjusted the preprocessing for MonoNPHM.
Specifically, you can look at the preprocessing [script](https://github.com/SimonGiebenhain/MonoNPHM/blob/main/scripts/data_processing/compute_fields_new.py), where I add a `REMOVE_LARGE_FACES` flag, which removes most of the larger interpolated faces.

Otherwise, I used everything fro training, except for a few individual expressions where the subjects moved too much during a capture, see `bad_scans` [here](https://github.com/SimonGiebenhain/MonoNPHM/blob/main/src/mononphm/env_paths.py).

**Comment by jseobyun** [comment]
Thanks for you kind explanation. I've totally understood and everything is clear.

Have a good day~!
