### ISSUE TITLE
Inference time for fitting point clouds

### ISSUE THREAD

**Issue by aabbas90** [SimonGiebenhain/NPHM#24]
Hi, 

Firstly thanks for making the code public with all of the details. I am curious about inference time for fitting point clouds which does not look to be close to real-time. It would be good if different approaches from the literature could be compared w.r.t. their compute time v/s quality of reconstruction. I could not find a comparison of inference times in the paper. Could you please comment on that? Thanks.

**Comment by SimonGiebenhain** [comment]
Hi @aabbas90,

you are correct that our method is quite slow, since that was never of any concern for us.
Depending on what you are looking for, decreasing the number of optimization steps will make the fitting faster at a cost of potentially worse quality. 

Espeically for fitting the identity taking a lot of steps is helpful. Once that is done and you only have to optimizer for per-frame expression and head pose parameters, you can likely reduce the number of steps significantly.

Sorry, I don't not know any number right now. Feel free to benchmark them yourself and share for others
